# MDD Symptoms meta analysis

Set up in process meta-analysis so that leave-one-out (LOO) can be swiftly generated.

In [157]:
import polars as pl
import numpy as np
from scipy.stats import chi2
import glob
from pathlib import Path, PurePath
import os

Symptom references

In [2]:
symptom_reference_tab = """
MDD1;depressed;Depressed mood most of the day, nearly every day
MDD2;anhedonia;Markedly diminished interest or pleasure in all, or almost all, activities most of the day, nearly every day
MDD3;weightChange;Significant change in weight or appetite
MDD3a;weightLoss;Significant weight loss or decrease in appetite
MDD3b;weightGain;Significant weight gain or increase in appetite
MDD4;sleepChange;Sleeping too much or not sleeping enough
MDD4a;sleepProb;Insomnia nearly every day
MDD4b;sleepMore;Hypersomnia nearly every day
MDD5;psychomotor;Changes in speed/amount of moving or speaking
MDD5a;psychomotorFast;Psychomotor agitation nearly every day
MDD5b;psychomotorSlow;Psychomotor retardation nearly every day
MDD6;fatigue;Fatigue or loss of energy nearly every day
MDD7;worthless;Feelings of worthlessness or excessive or inappropriate guilt
MDD8;concentration;Diminished ability to think or concentrate, or indecisiveness
MDD9;death;Recurrent thoughts of death or suicide or a suicide attempt or a specific plan for attempting suicide
"""

symptom_reference_dat = [line.split(';') for line in symptom_reference_tab.strip().split('\n')]
references = [symp[0] for symp in symptom_reference_dat]
abbrevs = [symp[1] for symp in symptom_reference_dat]
descriptions = [symp[0] for symp in symptom_reference_dat]
#dsm_mdd_symptoms_reference_df = pd.DataFrame(symptom_reference_dat,
#    columns=['Reference', 'Symptom Abbrev.', 'Description'])
dsm_mdd_symptoms_reference_df = pl.DataFrame(
    {
        "reference": references,
        "abbrev": abbrevs,
        "description": descriptions
    }
)
dsm_mdd_symptoms_reference_df

shape: (15, 3)
┌───────────┬─────────────────┬─────────────┐
│ reference ┆ abbrev          ┆ description │
│ ---       ┆ ---             ┆ ---         │
│ str       ┆ str             ┆ str         │
╞═══════════╪═════════════════╪═════════════╡
│ MDD1      ┆ depressed       ┆ MDD1        │
│ MDD2      ┆ anhedonia       ┆ MDD2        │
│ MDD3      ┆ weightChange    ┆ MDD3        │
│ MDD3a     ┆ weightLoss      ┆ MDD3a       │
│ MDD3b     ┆ weightGain      ┆ MDD3b       │
│ …         ┆ …               ┆ …           │
│ MDD5b     ┆ psychomotorSlow ┆ MDD5b       │
│ MDD6      ┆ fatigue         ┆ MDD6        │
│ MDD7      ┆ worthless       ┆ MDD7        │
│ MDD8      ┆ concentration   ┆ MDD8        │
│ MDD9      ┆ death           ┆ MDD9        │
└───────────┴─────────────────┴─────────────┘

Read list of cohorts and groupings

In [110]:
cohorts_df = pl.read_csv("meta/cohort_alignment.txt", separator="\t")
samples_df = pl.read_csv("sumstats/cohorts_samples.txt", separator="\t")
cohorts_reference_df = (
  cohorts_df
  .join(dsm_mdd_symptoms_reference_df, on="reference")
  .join(samples_df, on = ["study", "reference"])
)
cohorts_reference_df

shape: (221, 13)
┌─────────────────────┬───────┬────────┬───────┬───┬────────────┬────────────┬───────────┬─────────┐
│ filename            ┆ study ┆ cohort ┆ group ┆ … ┆ N_controls ┆ N_eff_half ┆ LAMBDA-GC ┆ N-SNPs  │
│ ---                 ┆ ---   ┆ ---    ┆ ---   ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---     │
│ str                 ┆ str   ┆ str    ┆ str   ┆   ┆ i64        ┆ i64        ┆ f64       ┆ i64     │
╞═════════════════════╪═══════╪════════╪═══════╪═══╪════════════╪════════════╪═══════════╪═════════╡
│ daner_MDD1_bidi1.gz ┆ bidi1 ┆ PGC    ┆ Clin  ┆ … ┆ 411        ┆ 405        ┆ 0.999     ┆ 6892871 │
│ daner_MDD1_gep3.gz  ┆ gep3  ┆ PGC    ┆ Clin  ┆ … ┆ 243        ┆ 230        ┆ 1.004     ┆ 6331102 │
│ daner_MDD1_nes1.gz  ┆ nes1  ┆ PGC    ┆ Clin  ┆ … ┆ 161        ┆ 284        ┆ 0.996     ┆ 7016537 │
│ daner_MDD1_rot4.gz  ┆ rot4  ┆ PGC    ┆ Clin  ┆ … ┆ 164        ┆ 78         ┆ 1.021     ┆ 5401975 │
│ daner_MDD1_stm2.gz  ┆ stm2  ┆ PGC    ┆ Clin  ┆ … ┆ 67         ┆ 124        ┆ 0.947     ┆ 6450212 │
│ …                   ┆ …     ┆ …      ┆ …     ┆ … ┆ …          ┆ …          ┆ …         ┆ …       │
│ daner_dichotomized_ ┆ janpy ┆ janpy  ┆ Clin  ┆ … ┆ 142        ┆ 217        ┆ 0.988     ┆ 6544017 │
│ Pessimistic…        ┆       ┆        ┆       ┆   ┆            ┆            ┆           ┆         │
│ daner_dichotomized_ ┆ janpy ┆ janpy  ┆ Clin  ┆ … ┆ 385        ┆ 278        ┆ 1.015     ┆ 6633726 │
│ Reduced_App…        ┆       ┆        ┆       ┆   ┆            ┆            ┆           ┆         │
│ daner_dichotomized_ ┆ janpy ┆ janpy  ┆ Clin  ┆ … ┆ 100        ┆ 166        ┆ 0.986     ┆ 6508959 │
│ Reduced_Sle…        ┆       ┆        ┆       ┆   ┆            ┆            ┆           ┆         │
│ daner_dichotomized_ ┆ janpy ┆ janpy  ┆ Clin  ┆ … ┆ 16         ┆ 31         ┆ 0.946     ┆ 5934311 │
│ Sadness_2.m…        ┆       ┆        ┆       ┆   ┆            ┆            ┆           ┆         │
│ daner_dichotomized_ ┆ janpy ┆ janpy  ┆ Clin  ┆ … ┆ 475        ┆ 201        ┆ 1.001     ┆ 6652864 │
│ Suicidal_Th…        ┆       ┆        ┆       ┆   ┆            ┆            ┆           ┆         │
└─────────────────────┴───────┴────────┴───────┴───┴────────────┴────────────┴───────────┴─────────┘

Mark information with dataset name to match tidied sumstats, and group into meta-analysis sets.

In [111]:
cohorts_datasets = cohorts_reference_df.with_columns(
    (pl.col("study") + "-" + pl.col("group") + "-" + pl.col("reference") + "-ref").alias("dataset"),
    (pl.col("group") + "-" + pl.col("reference") + "_" + pl.col("abbrev")).alias("metaset")
)

Dataset list for primary group/symptom combinations.

In [112]:
metasets = (
    cohorts_datasets
    .select(pl.col("dataset"), pl.col("metaset"))
    .unique()
)
metasets

shape: (221, 2)
┌───────────────────────┬────────────────────────────┐
│ dataset               ┆ metaset                    │
│ ---                   ┆ ---                        │
│ str                   ┆ str                        │
╞═══════════════════════╪════════════════════════════╡
│ GenScot-Clin-MDD1-ref ┆ Clin-MDD1_depressed        │
│ EstBB-Comm-MDD3b-ref  ┆ Comm-MDD3b_weightGain      │
│ bidi1-Clin-MDD3b-ref  ┆ Clin-MDD3b_weightGain      │
│ gep3-Clin-MDD7-ref    ┆ Clin-MDD7_worthless        │
│ qio2-Clin-MDD9-ref    ┆ Clin-MDD9_death            │
│ …                     ┆ …                          │
│ mmi2-Clin-MDD5a-ref   ┆ Clin-MDD5a_psychomotorFast │
│ ALSPAC-Comm-MDD8-ref  ┆ Comm-MDD8_concentration    │
│ janpy-Clin-MDD2-ref   ┆ Clin-MDD2_anhedonia        │
│ UKBB-Comm-MDD4a-ref   ┆ Comm-MDD4a_sleepProb       │
│ bidi1-Clin-MDD4a-ref  ┆ Clin-MDD4a_sleepProb       │
└───────────────────────┴────────────────────────────┘

Open tidied sumstats. Cast `CHR` column to string so the type is the same across datasets. Add dataset name as a column and assign to metasets (only process Community cohorts metasets for now).

In [6]:
sumstats_paths = glob.glob("sumstats/tidy/*-Comm-*.parquet")
sumstats = (
    pl.concat(
        [pl.scan_parquet(path).cast({"CHR": pl.String}).with_columns(pl.lit(Path(path).stem).alias("dataset")) for path in sumstats_paths],
        how = "vertical"
    ).join(metasets.lazy(), on = "dataset", how = "inner")
)

Weight statistics in preperation for meta-analysis.

In [7]:
weights = (
        sumstats.with_columns(
            (1 / (pl.col("SE") ** 2)).alias("ivw")
        )
        .with_columns(
            (pl.col("B") * pl.col("ivw")).alias("wBETA"),
            (pl.col("INFO") * pl.col("N")).alias("wINFO"),
            (pl.col("EAF") * pl.col("CaseN")).alias("wEAF")
        )
)

Perform meta-analysis grouped by metaset and variant

In [8]:
meta = (
  weights
  .group_by("metaset", "CHR", "POS_38", "POS_37", "RSID", "EffectAllele", "OtherAllele")
  .agg(
      (pl.sum("wBETA") /  pl.sum("ivw")).exp().alias("OR"),
      (1 / pl.sum("ivw")).sqrt().alias("LOG_OR_SE"),
      (pl.sum("wINFO") / pl.sum("N")).alias("INFO"),
      (pl.sum("wEAF") / pl.sum("CaseN")).alias("EAF"),
      pl.sum("CaseN"),
      pl.sum("ControlN"),
      pl.sum("EffectiveN")
  )
)

Calculate meta-analysis and sink dataset.

In [9]:
meta.sink_parquet(
  pl.PartitionBy("meta/tidy", key = ["metaset", "CHR"]),
  mkdir = True
)

Leave-one-out meta-analyses. Full merge of datasets in the same metaset, then remove dataset rows to construct LOO metasets.

In [122]:
loo_sets = (
    cohorts_datasets
    .select(
      pl.col("dataset"),
      pl.col("study"),
      pl.col("metaset"),
      (pl.col("group") + "-" + "excl_" + pl.col("study") + "-" + pl.col("reference") + "_" + pl.col("abbrev")).alias("looset"),
      pl.col("N_cases"),
      pl.col("N_controls"),
      pl.col("N_eff_half")
    )
    .unique()
)

loo_metasets = (
  loo_sets
  .select(
    pl.col("dataset"),
    pl.col("metaset"),
    pl.col("study").alias("target"),
    pl.col("N_cases"),
    pl.col("N_controls"),
    pl.col("N_eff_half")
  )
  .join(loo_sets, on = "metaset", how = "full")
  .filter(pl.col("target") != pl.col("study"))
  .select(
    pl.col("dataset"),
    pl.col("target").alias("study"),
    pl.col("N_cases"),
    pl.col("N_controls"),
    pl.col("N_eff_half"),
    pl.col("looset").alias("metaset"),
    pl.col("study").alias("loo"))
  .partition_by("metaset", as_dict = True)
)

Prototype helper functions for meta-analysis.

In [ ]:
# scan a sumstats parquet and add file stem as a column
def scan_sumstats(source):
  sumstats = (
    pl.scan_parquet(source)
    .cast({"CHR": pl.String})
    .with_columns(pl.lit(Path(source).stem).alias("dataset"))
  )
  return(sumstats)

def concat_sumstats(sources):
  sumstats = pl.concat(
    [scan_sumstats(source) for source in sources],
    how = "vertical"
  )
  return(sumstats)

In [170]:
def weight_sumstats(sumstats):
  weights = (
        sumstats.with_columns(
            (1 / (pl.col("SE") ** 2)).alias("ivw")
        )
        .with_columns(
            (pl.col("B") * pl.col("ivw")).alias("wBETA"),
            (pl.col("INFO") * pl.col("N")).alias("wINFO"),
            (pl.col("EAF") * pl.col("CaseN")).alias("wEAF")
        )
  )
  return(weights)

def ma_weights(weights):
    meta = (
        weights
        .group_by("CHR", "POS_38", "POS_37", "RSID", "EffectAllele", "OtherAllele")
        .agg(
            (pl.sum("wBETA") /  pl.sum("ivw")).exp().alias("OR"),
            (1 / pl.sum("ivw")).sqrt().alias("LOG_OR_SE"),
            (pl.sum("wINFO") / pl.sum("N")).alias("INFO"),
            (pl.sum("wEAF") / pl.sum("CaseN")).alias("EAF"),
            pl.sum("CaseN"),
            pl.sum("ControlN"),
            pl.sum("EffectiveN")
        )
        .with_columns(
            (
              ((pl.col("OR").log() ** 2) / (pl.col("LOG_OR_SE") ** 2))
              .map_batches(lambda s: pl.Series(chi2.sf(s.to_numpy(), 1).tolist()), return_dtype=pl.self_dtype())
            )
            .alias("P")
        )
    )
    return(meta)

def ma(sumstats):
   weights = weight_sumstats(sumstats)
   ma = ma_weights(weights)
   return(ma)

In [171]:
for loo, metaset in loo_metasets.items():
  # get dataset and construct paths to sources and sink
  datasets = metaset.get_column('dataset').to_list()
  sources = [os.path.join("sumstats", "tidy", dataset + ".parquet") for dataset in datasets]
  sink = os.path.join("meta/loo/" + loo[0] + ".parquet")
  csv = os.path.join("meta/loo/" + loo[0] + ".csv")
  # run meta-analysis if it has not already been done
  if not os.path.exists(sink):
    # run the meta-analysis if all of the sources exist
    if(all([os.path.exists(source) for source in sources])):
      print("Processing " + loo[0])
      sumstats = concat_sumstats(sources)
      ma_sumstats = ma(sumstats)
      ma_sumstats.sink_parquet(
        pl.PartitionBy(
          sink,
          key = "CHR"
        ),
        mkdir = True
      )
      # sample size information
      samples = (
        metaset
        .select(
          pl.col("study"),
          pl.col("N_cases"),
          pl.col("N_controls"),
          pl.col("N_eff_half")
        )
      )
      samples_totals = pl.concat([samples, samples.select(pl.lit("Total").alias("study"), pl.col(pl.Int64).sum())])
      samples_totals.write_csv(csv)
    else:
      print("Missing sources for " + loo[0])
  else:
    print("Processed " + loo[0])

Missing sources for Clin-excl_qi3c-MDD4a_sleepProb
Missing sources for Clin-excl_rad3-MDD6_fatigue
Missing sources for Clin-excl_nes1-MDD7_worthless
Processing Comm-excl_EstBB-MDD3a_weightLoss
Missing sources for Clin-excl_GenScot-MDD5b_psychomotorSlow
Missing sources for Clin-excl_gens-MDD3a_weightLoss
Missing sources for Clin-excl_qio2-MDD4a_sleepProb
Missing sources for Clin-excl_GenScot-MDD9_death
Missing sources for Clin-excl_mmi2-MDD5a_psychomotorFast
Missing sources for Clin-excl_nes1-MDD3b_weightGain
Missing sources for Clin-excl_mmi2-MDD7_worthless
Missing sources for Clin-excl_gep3-MDD2_anhedonia
Missing sources for Clin-excl_AGDS-MDD2_anhedonia
Missing sources for Clin-excl_gep3-MDD5a_psychomotorFast
Missing sources for Clin-excl_gep3-MDD4a_sleepProb
Missing sources for Clin-excl_rad3-MDD9_death
Missing sources for Clin-excl_gep3-MDD7_worthless
Processing Comm-excl_EstBB-MDD1_depressed
Missing sources for Clin-excl_rau2-MDD3b_weightGain
Missing sources for Clin-excl_grnd-MDD2_anhedonia
Missing sources for Clin-excl_gens-MDD3b_weightGain
Missing sources for Clin-excl_qi3c-MDD3a_weightLoss
Missing sources for Clin-excl_rau2-MDD4a_sleepProb
Missing sources for Clin-excl_qi3c-MDD3b_weightGain
Missing sources for Clin-excl_mmo4-MDD3a_weightLoss
Missing sources for Clin-excl_stm2-MDD3b_weightGain
Missing sources for Clin-excl_stm2-MDD5b_psychomotorSlow
Missing sources for Clin-excl_col3-MDD8_concentration
Missing sources for Clin-excl_GenScot-MDD8_concentration
Missing sources for Clin-excl_rad3-MDD4a_sleepProb
Missing sources for Clin-excl_qi3c-MDD9_death
Missing sources for Clin-excl_gep3-MDD3b_weightGain
Missing sources for Clin-excl_AGDS-MDD1_depressed
Missing sources for Clin-excl_gep3-MDD8_concentration
Processing Comm-excl_UKBB-MDD3a_weightLoss
Missing sources for Clin-excl_rau2-MDD5b_psychomotorSlow
Missing sources for Clin-excl_grnd-MDD4b_sleepMore
Missing sources for Clin-excl_col3-MDD5b_psychomotorSlow
Missing sources for Clin-excl_GenScot-MDD2_anhedonia
Missing sources for Clin-excl_gens-MDD9_death
Missing sources for Clin-excl_twg2-MDD3b_weightGain
Missing sources for Clin-excl_gens-MDD2_anhedonia
Missing sources for Clin-excl_nes1-MDD4a_sleepProb
Missing sources for Clin-excl_bidi1-MDD8_concentration
Processing Comm-excl_EstBB-MDD7_worthless
Missing sources for Clin-excl_col3-MDD3a_weightLoss
Missing sources for Clin-excl_col3-MDD9_death
Missing sources for Clin-excl_AGDS-MDD8_concentration
Missing sources for Clin-excl_bidi1-MDD6_fatigue
Missing sources for Clin-excl_qi3c-MDD2_anhedonia
Missing sources for Clin-excl_qi3c-MDD5a_psychomotorFast
Missing sources for Clin-excl_rau2-MDD9_death
Processing Comm-excl_ALSPAC-MDD4b_sleepMore
Missing sources for Clin-excl_gep3-MDD6_fatigue
Processing Comm-excl_UKBB-MDD2_anhedonia
Missing sources for Clin-excl_rad3-MDD2_anhedonia
Missing sources for Clin-excl_nes1-MDD5b_psychomotorSlow
Missing sources for Clin-excl_qio2-MDD5b_psychomotorSlow
Missing sources for Clin-excl_AGDS-MDD4b_sleepMore
Missing sources for Clin-excl_mmo4-MDD6_fatigue
Missing sources for Clin-excl_rad3-MDD5a_psychomotorFast
Missing sources for Clin-excl_mmi2-MDD4a_sleepProb
Missing sources for Clin-excl_rage-MDD3a_weightLoss
Processing Comm-excl_EstBB-MDD2_anhedonia
Missing sources for Clin-excl_gens-MDD5b_psychomotorSlow
Missing sources for Clin-excl_rad3-MDD3b_weightGain
Missing sources for Clin-excl_bidi1-MDD1_depressed
Missing sources for Clin-excl_bidi1-MDD3a_weightLoss
Missing sources for Clin-excl_col3-MDD7_worthless
Missing sources for Clin-excl_rde4-MDD4a_sleepProb
Missing sources for Clin-excl_mmo4-MDD5a_psychomotorFast
Missing sources for Clin-excl_qi3c-MDD7_worthless
Missing sources for Clin-excl_GenScot-MDD7_worthless
Missing sources for Clin-excl_qi6c-MDD5a_psychomotorFast
Missing sources for Clin-excl_twg2-MDD4a_sleepProb
Processing Comm-excl_UKBB-MDD3b_weightGain
Missing sources for Clin-excl_GenScot-MDD5a_psychomotorFast
Processing Comm-excl_UKBB-MDD4b_sleepMore
Missing sources for Clin-excl_gens-MDD5a_psychomotorFast
Processing Comm-excl_UKBB-MDD6_fatigue
Missing sources for Clin-excl_GenScot-MDD6_fatigue
Missing sources for Clin-excl_stm2-MDD4b_sleepMore
Missing sources for Clin-excl_gens-MDD6_fatigue
Processing Comm-excl_ALSPAC-MDD6_fatigue
Missing sources for Clin-excl_rot4-MDD3a_weightLoss
Missing sources for Clin-excl_rad3-MDD7_worthless
Missing sources for Clin-excl_qi6c-MDD3a_weightLoss
Missing sources for Clin-excl_gens-MDD8_concentration
Missing sources for Clin-excl_bidi1-MDD2_anhedonia
Missing sources for Clin-excl_AGDS-MDD7_worthless
Missing sources for Clin-excl_qi6c-MDD9_death
Processing Comm-excl_UKBB-MDD9_death
Processing Comm-excl_ALSPAC-MDD8_concentration
Missing sources for Clin-excl_twg2-MDD9_death
Missing sources for Clin-excl_nes1-MDD3a_weightLoss
Missing sources for Clin-excl_qio2-MDD9_death
Missing sources for Clin-excl_cof3-MDD5a_psychomotorFast
Missing sources for Clin-excl_janpy-MDD8_concentration
Missing sources for Clin-excl_rde4-MDD5b_psychomotorSlow
Missing sources for Clin-excl_rot4-MDD1_depressed
Missing sources for Clin-excl_qi6c-MDD4a_sleepProb
Processing Comm-excl_UKBB-MDD1_depressed
Missing sources for Clin-excl_mmo4-MDD4a_sleepProb
Missing sources for Clin-excl_GenScot-MDD4b_sleepMore
Missing sources for Clin-excl_bidi1-MDD3b_weightGain
Missing sources for Clin-excl_twg2-MDD3a_weightLoss
Missing sources for Clin-excl_rot4-MDD6_fatigue
Missing sources for Clin-excl_gens-MDD4a_sleepProb
Missing sources for Clin-excl_grnd-MDD4a_sleepProb
Missing sources for Clin-excl_janpy-MDD1_depressed
Missing sources for Clin-excl_twg2-MDD1_depressed
Missing sources for Clin-excl_nes1-MDD5a_psychomotorFast
Missing sources for Clin-excl_mmi2-MDD6_fatigue
Missing sources for Clin-excl_gens-MDD4b_sleepMore
Missing sources for Clin-excl_GenScot-MDD1_depressed
Processing Comm-excl_UKBB-MDD4a_sleepProb
Missing sources for Clin-excl_stm2-MDD1_depressed
Missing sources for Clin-excl_rde4-MDD9_death
Missing sources for Clin-excl_rad3-MDD4b_sleepMore
Missing sources for Clin-excl_nes1-MDD6_fatigue
Missing sources for Clin-excl_col3-MDD4a_sleepProb
Missing sources for Clin-excl_janpy-MDD2_anhedonia
Missing sources for Clin-excl_stm2-MDD9_death
Missing sources for Clin-excl_qi6c-MDD7_worthless
Missing sources for Clin-excl_rau2-MDD3a_weightLoss
Processing Comm-excl_EstBB-MDD8_concentration
Missing sources for Clin-excl_nes1-MDD9_death
Missing sources for Clin-excl_stm2-MDD3a_weightLoss
Missing sources for Clin-excl_janpy-MDD3a_weightLoss
Missing sources for Clin-excl_grnd-MDD3b_weightGain
Missing sources for Clin-excl_qio2-MDD5a_psychomotorFast
Processing Comm-excl_ALSPAC-MDD3b_weightGain
Missing sources for Clin-excl_gep3-MDD5b_psychomotorSlow
Missing sources for Clin-excl_bidi1-MDD7_worthless
Missing sources for Clin-excl_stm2-MDD7_worthless
Missing sources for Clin-excl_rad3-MDD5b_psychomotorSlow
Missing sources for Clin-excl_bidi1-MDD4a_sleepProb
Missing sources for Clin-excl_stm2-MDD2_anhedonia
Missing sources for Clin-excl_GenScot-MDD4a_sleepProb
Missing sources for Clin-excl_stm2-MDD6_fatigue
Missing sources for Clin-excl_AGDS-MDD9_death
Missing sources for Clin-excl_twg2-MDD8_concentration
Missing sources for Clin-excl_janpy-MDD9_death
Missing sources for Clin-excl_qi6c-MDD2_anhedonia
Missing sources for Clin-excl_janpy-MDD7_worthless
Missing sources for Clin-excl_col3-MDD5a_psychomotorFast
Missing sources for Clin-excl_gep3-MDD1_depressed
Missing sources for Clin-excl_AGDS-MDD5b_psychomotorSlow
Missing sources for Clin-excl_rad3-MDD8_concentration
Missing sources for Clin-excl_AGDS-MDD6_fatigue
Missing sources for Clin-excl_rot4-MDD9_death
Missing sources for Clin-excl_qio2-MDD3a_weightLoss
Missing sources for Clin-excl_GenScot-MDD3b_weightGain
Processing Comm-excl_UKBB-MDD7_worthless
Missing sources for Clin-excl_col3-MDD4b_sleepMore
Missing sources for Clin-excl_qi3c-MDD8_concentration
Missing sources for Clin-excl_qi6c-MDD6_fatigue
Processing Comm-excl_ALSPAC-MDD7_worthless
Missing sources for Clin-excl_grnd-MDD3a_weightLoss
Processing Comm-excl_ALSPAC-MDD9_death
Missing sources for Clin-excl_nes1-MDD2_anhedonia
Missing sources for Clin-excl_gep3-MDD3a_weightLoss
Missing sources for Clin-excl_nes1-MDD1_depressed
Missing sources for Clin-excl_col3-MDD3b_weightGain
Missing sources for Clin-excl_rau2-MDD4b_sleepMore
Missing sources for Clin-excl_AGDS-MDD3b_weightGain
Missing sources for Clin-excl_nes1-MDD4b_sleepMore
Processing Comm-excl_ALSPAC-MDD2_anhedonia
Missing sources for Clin-excl_qi3c-MDD6_fatigue
Missing sources for Clin-excl_grnd-MDD5b_psychomotorSlow
Missing sources for Clin-excl_AGDS-MDD5a_psychomotorFast
Missing sources for Clin-excl_grnd-MDD8_concentration
Processing Comm-excl_ALSPAC-MDD4a_sleepProb
Missing sources for Clin-excl_rage-MDD9_death
Missing sources for Clin-excl_janpy-MDD4a_sleepProb
Missing sources for Clin-excl_qi3c-MDD4b_sleepMore
Processing Comm-excl_UKBB-MDD8_concentration
Missing sources for Clin-excl_qi6c-MDD3b_weightGain
Missing sources for Clin-excl_grnd-MDD9_death
Missing sources for Clin-excl_GenScot-MDD3a_weightLoss
Missing sources for Clin-excl_gens-MDD7_worthless
Processing Comm-excl_ALSPAC-MDD3a_weightLoss
Missing sources for Clin-excl_stm2-MDD5a_psychomotorFast
Missing sources for Clin-excl_twg2-MDD6_fatigue
Missing sources for Clin-excl_qio2-MDD4b_sleepMore
Missing sources for Clin-excl_rot4-MDD2_anhedonia
Processing Comm-excl_EstBB-MDD6_fatigue
Missing sources for Clin-excl_rot4-MDD8_concentration
Missing sources for Clin-excl_rau2-MDD5a_psychomotorFast
Missing sources for Clin-excl_mmi2-MDD5b_psychomotorSlow
Missing sources for Clin-excl_mmi2-MDD9_death
Missing sources for Clin-excl_qi6c-MDD4b_sleepMore
Missing sources for Clin-excl_qi3c-MDD5b_psychomotorSlow
Missing sources for Clin-excl_qio2-MDD3b_weightGain
Missing sources for Clin-excl_mmo4-MDD7_worthless
Missing sources for Clin-excl_stm2-MDD8_concentration
Missing sources for Clin-excl_grnd-MDD5a_psychomotorFast
Missing sources for Clin-excl_mmo4-MDD5b_psychomotorSlow
Processing Comm-excl_EstBB-MDD9_death
Missing sources for Clin-excl_gep3-MDD4b_sleepMore
Missing sources for Clin-excl_rage-MDD5b_psychomotorSlow
Processing Comm-excl_ALSPAC-MDD1_depressed
Missing sources for Clin-excl_AGDS-MDD4a_sleepProb
Processing Comm-excl_EstBB-MDD3b_weightGain
Missing sources for Clin-excl_AGDS-MDD3a_weightLoss
Missing sources for Clin-excl_col3-MDD6_fatigue
Missing sources for Clin-excl_twg2-MDD2_anhedonia
Missing sources for Clin-excl_janpy-MDD5b_psychomotorSlow
Missing sources for Clin-excl_rage-MDD4a_sleepProb
Processing Comm-excl_EstBB-MDD4a_sleepProb
Missing sources for Clin-excl_rad3-MDD3a_weightLoss
Missing sources for Clin-excl_qi6c-MDD5b_psychomotorSlow
Missing sources for Clin-excl_nes1-MDD8_concentration
Missing sources for Clin-excl_qio2-MDD6_fatigue
Missing sources for Clin-excl_mmo4-MDD9_death
Missing sources for Clin-excl_mmi2-MDD3a_weightLoss
Missing sources for Clin-excl_qio2-MDD7_worthless
Processing Comm-excl_EstBB-MDD4b_sleepMore
Missing sources for Clin-excl_bidi1-MDD9_death

Output GZ sumstats for UK Biobank LOO.

In [153]:
ukb_loo_sumstats_paths = glob.glob("meta/loo/Comm-excl_UKBB*.parquet")
for source in ukb_loo_sumstats_paths:
  sumstats = (
    pl.scan_parquet(source)
    .sort(by = ["CHR", "POS_37"])
  )
  sumstats.sink_csv(str(PurePath(source).with_suffix(".tsv.gz")), compression = "gzip", separator="\t")